base-pkg/main/default/objects/Product2/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easy</fullName>
                <default>true</default>
                <label>Easy</label>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Hard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

base-pkg/main/default/objects/Product2/fields/HasColor__c.field-meta.xml
<CustomField>
    <fullName>HasColor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does this plant have colors, or is it simply green?</description>
    <label>Has Color?</label>
    <type>Checkbox</type>
</CustomField>

base-pkg-full/main/default/objects/Product2/fields/HasFlowers__c.field-meta.xml
<CustomField>
    <fullName>HasFlowers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does this plant flower?</description>
    <label>Has Flowers?</label>
    <type>Checkbox</type>
</CustomField>

base-pkg/main/default/objects/Product2/fields/HasVarieties__c.field-meta.xml
<CustomField>
    <fullName>HasVarieties__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If several subtypes are for sale for this plant.</description>
    <label>Has Varieties?</label>
    <type>Checkbox</type>
</CustomField>

base-pkg-full/main/default/objects/Product2/fields/IsPetFriendly__c.field-meta.xml
<CustomField>
    <fullName>IsPetFriendly__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this plant safe to pets, or is it toxic?</description>
    <label>Is Pet-Friendly?</label>
    <type>Checkbox</type>
</CustomField>

base-pkg-full/main/default/objects/Product2/fields/Light_Level__c.field-meta.xml
<CustomField>
    <fullName>Light_Level__c</fullName>
    <label>Light Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any</fullName>
                <default>true</default>
                <label>Any</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Bright</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

base-pkg/main/default/objects/Product2/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
                <default>true</default>
                <label>Small</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

base-pkg/main/default/objects/Product2/fields/SubVariety__c.field-meta.xml
<CustomField>
    <fullName>SubVariety__c</fullName>
    <description>If several varieties were available, this is the variant.</description>
    <label>Sub Variety</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

exp-pkg/main/default/classes/AuraMainHolderController.cls
public without sharing class AuraMainHolderController {
    @AuraEnabled
    public static Account GetMyAccount(){
        return [SELECT Id, Name FROM Account WHERE Id = :getAccountId() LIMIT 1];
    }
    
    @AuraEnabled
    public static List<orderItem> GetCartItems() {
        id acctID = getAccountID();

        List<orderItem> items = [
            SELECT id, unitprice, quantity, order.accountID, order.status, order.isdeleted, product2.name, product2.productcode, product2.subvariety__c, 
            product2.size__c, product2.light_level__c, product2.ispetfriendly__c, product2.hasvarieties__c, product2.hasflowers__c, product2.hascolor__c, 
            product2.difficulty__c 
            FROM orderItem 
            WHERE Order.AccountID = :acctID AND order.status = 'Draft' AND order.isdeleted = false
        ];

        return items;
    }
        
    @AuraEnabled(cacheable=true)
    public static List<PricebookEntry> AllProducts() {
        PricebookEntry[] products = [
            SELECT Id, FORMAT(UnitPrice), Product2.Name, Product2.SubVariety__c, 
                Product2.HasVarieties__c, Product2.Size__c, Product2.Difficulty__c, Product2.Light_Level__c, 
                Product2.HasColor__c, Product2.HasFlowers__c, Product2.IsPetFriendly__c, Product2.ProductCode
            FROM PricebookEntry
            WHERE IsActive = true AND IsDeleted = false AND ProductCode != null
        ];

        return products;
    }

    public static ID getAccountId() {
        ID currentUserId = UserInfo.getUserId();
        return [SELECT id, Contact.AccountId FROM User WHERE id = :currentUserId]?.Contact.AccountId;
    }
}