base-pkg/main/default/objects/Forum_Item__c/Forum_Item__c.object-meta.xml
<CustomObject>
    <label>Forum Item</label>
    <nameField>
        <displayFormat>Forum-{000000}</displayFormat>
        <label>Forum Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forum Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

base-pkg-full/main/default/objects/Forum_Item__c/fields/Child_Comments__c.field-meta.xml
<CustomField>
    <fullName>Child_Comments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Child Comments</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

base-pkg-full/main/default/objects/Forum_Item__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

base-pkg/main/default/objects/Forum_Item__c/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <label>Depth</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

base-pkg-full/main/default/objects/Forum_Item__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRemoved</label>
    <type>Checkbox</type>
</CustomField>

base-pkg/main/default/objects/Forum_Item__c/fields/Likes__c.field-meta.xml
<CustomField>
    <fullName>Likes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Likes</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

base-pkg/main/default/objects/Forum_Item__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Forum_Item__c</referenceTo>
    <relationshipLabel>Forum Items</relationshipLabel>
    <relationshipName>Forum_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

base-pkg-full/main/default/objects/Forum_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

exp-pkg/main/default/classes/AuraForumController.cls
public with sharing class AuraForumController {
    @AuraEnabled
    public static List<Forum_Item__c> GetTopLevelPosts() {
        List<Forum_Item__c> top = [
            SELECT Title__c, Content__c, Parent__r.name, Likes__c, Child_Comments__c 
            FROM Forum_Item__c WHERE Depth__c = 0 AND IsRemoved__c = false
        ];
        return top;
    }
    public static ID GetAccount(String acctName) {
        return [SELECT id FROM Account WHERE name= :acctName]?.id;
    }
}