base-pkg/main/default/objects/Forum_Item__c/Forum_Item__c.object-meta.xml
<CustomObject>
    <label>Forum Item</label>
    <nameField>
        <displayFormat>Forum-{000000}</displayFormat>
        <label>Forum Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forum Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

base-pkg/main/default/objects/Forum_Item__c/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <label>Depth</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

base-pkg-full/main/default/objects/Forum_Item__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRemoved</label>
    <type>Checkbox</type>
</CustomField>

exp-pkg/main/default/classes/AuraForumControllerTest.cls
@isTest
public class AuraForumControllerTest {
    @isTest
    public static void TP_NoExtraTopLevelPosts() {
        Set<ID> actualIDs = new Set<ID>();
        for (Forum_Item__c post : [SELECT id FROM Forum_Item__c WHERE Depth__c = 0 AND isRemoved__c = false]) {
            actualIDs.add(post.id);
        }

        Boolean success = true;
        for (Forum_Item__c post : AuraForumController.GetTopLevelPosts()) {
            if (!actualIDs.contains(post.id)) {
                success = false;
            }
        }
        System.assert(success);
    }
    @isTest
    public static void TP_GetsAllTopLevelPosts() {
        Set<ID> returnedIDs = new Set<ID>();
        for (Forum_Item__c post : AuraForumController.GetTopLevelPosts()) {
            returnedIDs.add(post.Id);
        }

        Boolean success = true;
        for (Forum_Item__c post : [SELECT id FROM Forum_Item__c WHERE Depth__c = 0 AND isRemoved__c = false]) {
            if (!returnedIDs.contains(post.id)) {
                success = false;
            }
        }
        System.assert(success);
    }
    // @isTest
    // public static void TP_PostLikeCreated() {
    //     Account a = SELECT
    // }
}